---
- name: Copy files from backend
  become: true
  copy:
    src: ~/project/artifact.tar.gz
    dest: /home/ubuntu/artifact.tar.gz

- name: remove dependencies that are no longer required
  become: yes
  apt:
    autoremove: yes

- name: "install dependencies."
  become: yes
  apt:
    name: ["nodejs", "npm"]
    state: latest
    update_cache: yes

- name: prepare binaries
  become: true
  shell: |
    cd /home/ubuntu
    tar xvzf artifact.tar.gz -C .

- name: Start PM2
  become: true
  shell: |
    cd /home/ubuntu/
    sudo npm install -g npm@latest
    sudo npm install -g webpack-dev-server
    sudo npm install
    sudo npm run build
    sudo pm2 stop default
    sudo pm2 start npm --name backend -- start