version: 2.1

orbs: 
  slack: circleci/slack@4.10.1

executors:
  my-node-executor:
    docker:
      - image: circleci/node:13.8.0

commands:
  slack-notifications:
    description: Provide slack notifications about jobs status.
    steps:
      - slack/notify:
          channel: notify
          mentions: @jean.paul
          event: fail
          template: basic_fail_1

      - slack/notify:
          channel: notify
          mentions: @here
          event: pass
          template: basic_success_1

jobs:
  build-frontend:
    executor: my-node-executor
    steps:
      - checkout
      - restore_cache:
          keys: [frontend-build]
      - run:
          name: Build front-end
          command: |
            cd frontend
            npm install
            npm run build
      - save_cache:
          paths: [frontend/node_modules]
          key: frontend-build
      - slack-notifications

  build-backend:
    executor: my-node-executor
    steps:
      - checkout
      - restore_cache:
          keys: [backend-build]
      - run:
          name: Back-end build
          command: |
            cd backend
            npm install
            npm run build
      - save_cache:
          paths: [backend/node_modules]
          key: backend-build
      - slack/notify:
          channel: notify
          event: fail
          template: basic_fail_1

  test-frontend:
    executor: my-node-executor
    steps:
      - checkout
      - restore_cache:
          keys: [frontend-build]
      - run:
          name: testing frontend
          command: |
            cd frontend
            npm run test
      - slack/notify:
          channel: notify
          event: fail
          template: basic_fail_1

  test-backend:
    executor: my-node-executor
    steps:
      - checkout
      - restore_cache:
          keys: [backend-build]
      - run:
          name: testing backend
          command: |
            cd backend
            npm run test
      - slack/notify:
          channel: notify
          event: fail
          template: basic_fail_1

  scan-frontend:
    executor: my-node-executor
    steps:
      - checkout
      - restore_cache:
          keys: [frontend-build]
      - run:
          name: scanning-frontend
          command: |
            cd frontend
            npm audit fix --audit-level=critical --force
      - slack-notifications

  scan-backend:
    executor: my-node-executor
    steps:
      - checkout
      - restore_cache:
          keys: [backend-build]
      - run:
          name: scanning-backend
          command: |
            cd backend
            npm audit fix --audit-level=critical --force
      - slack/notify:
          channel: notify
          event: fail
          template: basic_fail_1

workflows:
  default:
    jobs:
      - build-frontend:
          context: [circle notify]
      - build-backend
      - test-frontend:
          requires: [build-frontend]
      - test-backend:
          requires: [build-backend]
      - scan-backend:
          requires: [build-backend]
      - scan-frontend:
          requires: [build-frontend]
          context: [circle notify]
